(eval-when (:compile-toplevel)
  (defpackage :ld48 (:use :common-lisp :lispbuilder-sdl))
  (in-package :ld48)
  (mapcar #'load '("settings.lisp" "utilities.lisp" "creature.lisp" "testing.lisp")))

(defvar *box-x* 5)
(defvar *box-y* 5)

(defparameter *creatures* (make-creatures *num-creatures*))

(defun key-handler (key)
  (flet ((key-is (key-to-test) (key= key-to-test key)))
    (cond ((key-is :sdl-key-up) (setf *box-y* (- *box-y* 5)))
	  ((key-is :sdl-key-down) (setf *box-y* (+ *box-y* 5)))
	  ((key-is :sdl-key-right) (setf *box-x* (+ *box-x* 5)))
	  ((key-is :sdl-key-left) (setf *box-x* (- *box-x* 5)))
	  ((key-is :sdl-key-escape) (push-quit-event)))))

(defun run-game ()
  (with-init ()
    (if *fullscreen?* (window *WIDTH* *HEIGHT* :fullscreen t) (window *WIDTH* *HEIGHT*))
    (enable-key-repeat 1 1)
    (setf (frame-rate) 60)
    (with-events ()
      (:quit-event () t)
      (:key-down-event (:key key) (key-handler key))
      (:idle ()
	     (clear-display *black*)
	     (sdl-gfx:draw-circle (point :x *box-x* :y *box-y*) 20 :color *white*)
	     (mapcar #'draw *creatures*)
	     (tick)
	     (on-tick 10 (mapcar #'move *creatures*))
	     (update-display)))))
